# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  
    config.vm.define "b1" do |b1|
      b1.vm.box = "ubuntu/trusty64"
      b1.vm.hostname = "b1"
      b1.vm.network "private_network", ip: "192.168.33.1"
    end
  
    config.vm.define "b2" do |b2|
      b2.vm.box = "nrel/CentOS-6.5-x86_64"
      b2.vm.hostname = "b2"
      b2.vm.network "private_network", ip: "192.168.33.2"
      b2.vm.network "forwarded_port", guest: 80, host:8080
    end
    
    config.vm.define "b3" do |b3|
      b3.vm.box = "nrel/CentOS-6.5-x86_64"
      b3.vm.hostname = "b3"
      b3.vm.network "private_network", ip: "192.168.33.3"
    end
  
end