Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/w16s-sql17d"
  config.vm.box_version = "0.8.0"

  config.vm.provider "virtualbox" do |vb|
   vb.gui = true
   vb.memory = "1024"
  end

end
